# Site settings
name: Agung Nugroho
title: Agung Nugroho
description: D3D ARCHITECTURAL VISUALIZATION
url: https://agung.cyou
baseurl: ''
email: agung.nugroggo@gmail.com
cover: 
logo: https://agung.cyou/img/icon.png
resume: 
social:
  - title: email
    url: mailto:agung.nugroggo@gmail.com
  - title: instagram
    url: https://instagram.com/nugroggo/


# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
